const products = [
  {
    id: 'rec43w3ipXvP28vog',
    title: 'high-back bench',
    company: 'ikea',
    image: 'https://images2.imgbox.com/89/59/6An8aqJL_o.jpeg',
    price: 9.99,
  },
  {
    id: 'rec4f2RIftFCb7aHh',
    title: 'albany table',
    company: 'marcos',
    image: 'https://images2.imgbox.com/7a/63/MSXCAbxy_o.jpeg',
    price: 79.99,
  },
  {
    id: 'rec8kkCmSiMkbkiko',
    title: 'accent chair',
    company: 'caressa',
    image: 'https://images2.imgbox.com/09/58/9oyIxnvq_o.jpeg',
    price: 25.99,
  },
  {
    id: 'recBohCqQsot4Q4II',
    title: 'wooden table',
    company: 'caressa',
    image: 'https://images2.imgbox.com/b0/e8/9RR6A859_o.jpeg',
    price: 45.99,
  },
  {
    id: 'recDG1JRZnbpRHpoy',
    title: 'dining table',
    company: 'caressa',
    image: 'https://images2.imgbox.com/26/1f/SRvvNeyh_o.jpeg',
    price: 6.99,
  },
  {
    id: 'recNWGyP7kjFhSqw3',
    title: 'sofa set',
    company: 'liddy',
    image: 'https://images2.imgbox.com/3f/a7/LUkaeKXQ_o.jpeg',
    price: 69.99,
  },
  {
    id: 'recZEougL5bbY4AEx',
    title: 'modern bookshelf',
    company: 'marcos',
    image: 'https://images2.imgbox.com/f6/9b/oU89hRrp_o.jpeg',
    price: 8.99,
  },
  {
    id: 'recjMK1jgTb2ld7sv',
    title: 'emperor bed',
    company: 'liddy',
    image: 'https://images2.imgbox.com/ea/5d/L23N0ZhH_o.jpeg',
    price: 21.99,
  },
  {
    id: 'recmg2a1ctaEJNZhu',
    title: 'utopia sofa',
    company: 'marcos',
    image: 'https://images2.imgbox.com/9e/74/Lg3Ukpvo_o.jpeg',
    price: 39.95,
  },
  {
    id: 'recvKMNR3YFw0bEt3',
    title: 'entertainment center',
    company: 'liddy',
    image: 'https://images2.imgbox.com/60/63/tkwXJAHY_o.jpeg',
    price: 29.98,
  },
  {
    id: 'recxaXFy5IW539sgM',
    title: 'albany sectional',
    company: 'ikea',
    image: 'https://images2.imgbox.com/05/35/dYOcfc1x_o.jpeg',
    price: 10.99,
  },
  {
    id: 'recyqtRglGNGtO4Q5',
    title: 'leather sofa',
    company: 'liddy',
    image: 'https://images2.imgbox.com/81/85/PWzn2azi_o.jpeg',
    price: 9.99,
  },
];

